# Generated by Django 5.0 on 2024-07-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='ایمیل ارتباطی'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='phone_number',
            field=models.CharField(max_length=100, null=True, verbose_name='شماره تلفن ارتباظی'),
        ),
    ]
