# Generated by Django 5.0 on 2024-07-07 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_aboutus_email_alter_aboutus_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
