# Generated by Django 5.0 on 2024-06-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_cover_image_article_is_active_article_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='id دسته بندی'),
        ),
    ]
