# Generated by Django 5.0 on 2024-06-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slide_show',
            field=models.BooleanField(default=False, verbose_name='در اسلایدر نشان داده شود / نشود'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='تصویر کاور'),
        ),
    ]
