# Generated by Django 5.0 on 2024-07-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_remove_comment_content_remove_comment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
