# Generated by Django 5.0 on 2024-07-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_comment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='تصویر')),
                ('title', models.CharField(max_length=300, null=True, verbose_name='عنوان')),
                ('author', models.CharField(max_length=200, verbose_name='نویسنده')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=200, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, verbose_name='عنوان در url'),
        ),
    ]
