# Generated by Django 5.0 on 2024-07-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_gallery_alter_article_author_alter_article_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'گزارش تصویری', 'verbose_name_plural': 'گزارش های تصویری'},
        ),
    ]
