# Generated by Django 5.0 on 2024-07-22 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_aboutus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
    ]
