# Generated by Django 5.0 on 2024-07-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_delete_aboutus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
