# Generated by Django 5.0 on 2024-07-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='تصویر')),
                ('title', models.CharField(max_length=300, null=True, verbose_name='عنوان')),
                ('author', models.CharField(max_length=200, verbose_name='نویسنده')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'گزارش تصویری',
                'verbose_name_plural': 'گزارش های تصویری',
            },
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'گالری تصویر', 'verbose_name_plural': 'گالری تصاویر'},
        ),
    ]
