# Generated by Django 5.0 on 2024-07-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta_urls', models.URLField(max_length=100, verbose_name='لینک اینستاگرام')),
                ('yt_urls', models.URLField(max_length=100, verbose_name='لینک یوتیوب')),
                ('linkedin_urls', models.URLField(max_length=100, verbose_name='لینک لینکداین')),
                ('fb_urls', models.URLField(max_length=100, verbose_name='لینک فیسبوک')),
                ('tt_urls', models.URLField(max_length=100, verbose_name='لینک توییتر')),
            ],
            options={
                'verbose_name': 'لینک های فوتر',
                'verbose_name_plural': 'مدیریت لینک های فوتر',
            },
        ),
    ]
