# Generated by Django 5.0 on 2024-07-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0002_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='fb_urls',
            field=models.URLField(blank=True, max_length=100, verbose_name='لینک فیسبوک'),
        ),
        migrations.AlterField(
            model_name='links',
            name='insta_urls',
            field=models.URLField(blank=True, max_length=100, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='links',
            name='linkedin_urls',
            field=models.URLField(blank=True, max_length=100, verbose_name='لینک لینکداین'),
        ),
        migrations.AlterField(
            model_name='links',
            name='tt_urls',
            field=models.URLField(blank=True, max_length=100, verbose_name='لینک توییتر'),
        ),
        migrations.AlterField(
            model_name='links',
            name='yt_urls',
            field=models.URLField(blank=True, max_length=100, verbose_name='لینک یوتیوب'),
        ),
    ]
