# Generated by Django 5.0 on 2024-07-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0003_alter_links_fb_urls_alter_links_insta_urls_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.TextField(null=True, verbose_name='شهر یا منطقه')),
                ('street', models.TextField(null=True, verbose_name='خیابان یا محله')),
                ('post_code', models.TextField(null=True, verbose_name='کد پستی یا شماره تلفن')),
            ],
            options={
                'verbose_name': 'آدرس در فوتر',
                'verbose_name_plural': 'مدیریت آدرس در فوتر',
            },
        ),
    ]
