# Generated by Django 5.0 on 2024-07-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0005_alter_address_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='post_code',
            field=models.CharField(max_length=50, null=True, verbose_name='کد پستی یا شماره تلفن'),
        ),
    ]
