# Generated by Django 5.0 on 2024-07-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0007_alter_address_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=90, null=True, verbose_name='شهر یا منطقه'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.TextField(max_length=110, null=True, verbose_name='خیابان یا محله'),
        ),
    ]
