# Generated by Django 5.0 on 2024-07-25 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0008_alter_address_city_alter_address_street'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='fb_urls',
            new_name='rubika_urls',
        ),
    ]
