# Generated by Django 5.0 on 2024-07-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0009_rename_fb_urls_links_rubika_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='yt_urls',
        ),
        migrations.AddField(
            model_name='links',
            name='bale_urls',
            field=models.URLField(blank=True, max_length=100, verbose_name='لینک بله'),
        ),
        migrations.AlterField(
            model_name='links',
            name='rubika_urls',
            field=models.URLField(blank=True, max_length=100, verbose_name='لینک روبیکا'),
        ),
    ]
