# Generated by Django 5.0 on 2024-07-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize', '0010_remove_links_yt_urls_links_bale_urls_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='linkedin_urls',
        ),
        migrations.RemoveField(
            model_name='links',
            name='tt_urls',
        ),
        migrations.AddField(
            model_name='links',
            name='eita_urls',
            field=models.URLField(blank=True, max_length=100, verbose_name='لینک ایتا'),
        ),
    ]
